-- MySQL Script generated by MySQL Workbench
-- Fri Feb 14 22:35:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema accessories-vault
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `accessories-vault` ;

-- -----------------------------------------------------
-- Schema accessories-vault
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `accessories-vault` DEFAULT CHARACTER SET utf8mb4 ;
USE `accessories-vault` ;

-- -----------------------------------------------------
-- Table `accessories-vault`.`device_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accessories-vault`.`device_type` ;

CREATE TABLE IF NOT EXISTS `accessories-vault`.`device_type` (
  `type_id` TINYINT(2) UNSIGNED NOT NULL,
  `type_name` VARCHAR(45) NOT NULL,
  `type_rentable` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `accessories-vault`.`device_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accessories-vault`.`device_subject` ;

CREATE TABLE IF NOT EXISTS `accessories-vault`.`device_subject` (
  `devicesub_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `devicesub_name` VARCHAR(45) NOT NULL,
  `devicesub_type` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
  `devicesub_rentable` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
  `create_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`devicesub_id`),
  INDEX `ToolType_idx` (`devicesub_type` ASC) ,
  CONSTRAINT `device-devicetype`
    FOREIGN KEY (`devicesub_type`)
    REFERENCES `accessories-vault`.`device_type` (`type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `accessories-vault`.`device_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accessories-vault`.`device_list` ;

CREATE TABLE IF NOT EXISTS `accessories-vault`.`device_list` (
  `device_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `device_subjectid` INT(10) UNSIGNED NOT NULL,
  `device_status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `device_lock` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `add_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`device_id`),
  INDEX `device-devicesubject_idx` (`device_subjectid` ASC) ,
  CONSTRAINT `device-devicesubject`
    FOREIGN KEY (`device_subjectid`)
    REFERENCES `accessories-vault`.`device_subject` (`devicesub_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `accessories-vault`.`maintenance_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accessories-vault`.`maintenance_request` ;

CREATE TABLE IF NOT EXISTS `accessories-vault`.`maintenance_request` (
  `req_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `req_deviceid` INT(10) UNSIGNED NOT NULL,
  `req_symptom` VARCHAR(150) NULL DEFAULT NULL,
  `req_location` VARCHAR(150) NULL DEFAULT NULL,
  `req_closed` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `req_priority` MEDIUMINT(4) UNSIGNED NULL DEFAULT NULL,
  `req_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`req_id`),
  UNIQUE INDEX `req_deviceid_UNIQUE` (`req_deviceid` ASC) ,
  CONSTRAINT `maintaindeviceid`
    FOREIGN KEY (`req_deviceid`)
    REFERENCES `accessories-vault`.`device_list` (`device_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
